### ISSUE TITLE
Consider compile into es5 for cjs bundle

### ISSUE THREAD

**Issue by 3Shain** [amoutonbrady/vite-plugin-solid#8]
It raises error because my nodejs doesn't support `?.` (version 12.16.3)

```
failed to load config from /Users/sanshain/realkairo/apps/solid-app/vite.config.ts
error when starting dev server:
/Users/sanshain/realkairo/node_modules/vite-plugin-solid/dist/cjs/index.js:29
      userConfig.resolve.alias = normalizeAliases(userConfig.resolve?.alias);
                                                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/sanshain/realkairo/apps/solid-app/vite.config.ts:30:43)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.require.extensions.<computed> [as .ts] (/Users/sanshain/realkairo/node_modules/vite/dist/node/chunks/dep-efe32886.js:46235:20)
```

**Comment by MrFoxPro** [comment]
Use babel

**Comment by 3Shain** [comment]
> Use babel

I think you don't get my point. No sense to introduce babel here if I just want to use a _node_ library.

This problem can be easily fixed by changing the target to es5 in tsconfig.json, or just use a higher version node.

**Comment by amoutonbrady** [comment]
Hi @3Shain, I see your issue. I reckon I didn't put much thoughts into that as I considered that most environment using vite would end up using relatively recent version of node / browser. That being said this is a valid point that doesn't involve much changes.

I'll lower the target for CJS.

Thanks for bringing this to my attention and sorry for the delay :)
